<?php

namespace Tests\Feature;

use App\Models\Note;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class NotesApiTest extends TestCase
{
    /*
     * Resets the database state between tests.
     *
     * This prevents data created in one test from affecting another.
     * Each test should be able to run independently.
     */
    use RefreshDatabase;

    /**
     * Verifies that the application home page is accessible.
     *
     * HTTP 200 means the request was successfully processed.
     */
    public function test_the_application_returns_a_successful_response(): void
    {
        $response = $this->get('/');

        $response->assertStatus(200);
    }

    /**
     * Verifies the endpoint responsible for listing notes.
     *
     * Since the database starts empty for this test, we expect:
     * - GET /notes to return HTTP 200;
     * - the "data" key to exist;
     * - "data" to initially contain an empty array.
     */
    public function test_notes_endpoint_returns_successful_response(): void
    {
        $response = $this->getJson('/notes');

        $response->assertStatus(200);

        $response->assertJson([
            'data' => [],
        ]);
    }

    /**
     * Verifies that a valid note can be created.
     *
     * This test guarantees three behaviors:
     *
     * 1. POST /notes accepts a valid title and content;
     * 2. the API responds with HTTP 201 (Created);
     * 3. the note is actually persisted in the database.
     */
    public function test_note_successful_created(): void
    {
        $response = $this->postJson('/notes', [
            'title' => 'First note',
            'content' => 'This was a successful POST request to the API.',
        ]);

        // 201 means a new resource was successfully created.
        $response->assertStatus(201);

        // Confirms that the JSON response contains the submitted data.
        $response->assertJson([
            'title' => 'First note',
            'content' => 'This was a successful POST request to the API.',
        ]);

        /*
         * Confirms that the API did not only return the submitted data:
         * the note must actually exist in the database.
         */
        $this->assertDatabaseHas(Note::class, [
            'title' => 'First note',
            'content' => 'This was a successful POST request to the API.',
        ]);
    }

    /**
     * Verifies validation for the title field.
     *
     * Content is valid so that only title is responsible
     * for the validation failure.
     *
     * An invalid request should return HTTP 422.
     */
    public function test_post_empty_title(): void
    {
        $response = $this->postJson('/notes', [
            'title' => '',
            'content' => 'Some content',
        ]);

        $response
            ->assertUnprocessable()
            ->assertJsonValidationErrors(['title']);
    }

    /**
     * Verifies validation for the content field.
     *
     * Title is valid so that only content is responsible
     * for the validation failure.
     */
    public function test_post_empty_content(): void
    {
        $response = $this->postJson('/notes', [
            'title' => 'Some title',
            'content' => '',
        ]);

        $response
            ->assertUnprocessable()
            ->assertJsonValidationErrors(['content']);
    }

    /**
     * Verifies that a specific note can be retrieved by its ID.
     *
     * First, a Note is created directly with Eloquent.
     * The database generates the ID when save() is executed.
     *
     * Then GET /notes/{id} is called using the real generated ID
     * and the API response is checked against the stored note.
     */
    public function test_note_has_valid_fields(): void
    {
        $note = new Note;

        $note->title = 'A brief note on how I want to kill ChatGPT';
        $note->content = '...just kidding.';

        $note->save();

        /*
         * After save(), the model object receives the ID
         * generated by the database.
         */
        $note_id = $note->id;
        $note_title = $note->title;
        $note_content = $note->content;

        $response = $this->getJson("/notes/{$note_id}");

        $response->assertStatus(200);

        $response->assertJson([
            'id' => $note_id,
            'title' => $note_title,
            'content' => $note_content,
        ]);
    }

    /**
     * Verifies the behavior when requesting a note that does not exist.
     *
     * Since RefreshDatabase gives this test a clean database and
     * no note with this ID is created, HTTP 404 is expected.
     *
     * This behavior is provided by findOrFail()
     * inside the NoteController.
     */
    public function test_note_not_found(): void
    {
        $response = $this->getJson('/notes/999999');

        $response->assertNotFound();
    }

    public function test_update_note_not_found(): void
    {
        $response = $this->patchJson('/notes/999999', [
            'title' => 'New title',
            'content' => 'New content',
        ]);

        $response->assertNotFound();
    }

    public function test_notes_update(): void
    {
        $note = new Note;
        $note->title = 'A brief note on how I want to kill ChatGPT';
        $note->content = '...just kidding.';
        $note->save();

        $note_id = $note->id;

        $response = $this->patchJson("/notes/{$note_id}", [
            'title' => 'This is a new title',
            'content' => 'This is a new content',
        ]);

        $response->assertStatus(200);

        $response->assertJson([
            'id' => $note_id,
            'title' => 'This is a new title',
            'content' => 'This is a new content',
        ]);

        $this->assertDatabaseHas(Note::class, [
            'id' => $note_id,
            'title' => 'This is a new title',
            'content' => 'This is a new content',
        ]);
    }

    public function test_note_successfully_deleted()
    {
        $note = new Note;
        $note->title = 'A brief note';
        $note->content = 'Some note content.';
        $note->save();

        $note_id = $note->id;

        $response = $this->deleteJson("/notes/{$note_id}");

        $response->assertStatus(204);

        $this->assertDatabaseMissing(Note::class, ['id' => $note_id]);
    }
}
